name: commons-connect-client
recipe: lemp
services:
  appserver:
    config:
      php: .lando/php.ini
    build_as_root:
      - cd /app/.lando/ && ./setup-wordpress-files.sh && ./install-wp-cli.sh
      - cd /app/ && composer update
      - apt-get update && apt-get install subversion -y
    run:
      - /app/.lando/install-wordpress.sh
      - /app/bin/install-wp-tests.sh lemp lemp lemp database:3306
    command:
      - npm run start
    overrides:
      volumes:
        - .lando/wordpress:/wordpress
      environment:
        WP_CLI_CONFIG_PATH: /wordpress/wp-cli.yml
  appserver_nginx:
    overrides:
      volumes:
        - .lando/wordpress:/wordpress
config:
  php: 8.2
  database: mariadb
  xdebug: debug
  config:  
    vhosts: .lando/nginx.conf
tooling:
  wp:
    service: appserver
    description: Runs WP-CLI commands
    cmd: wp
  phpunit:
    service: appserver
    description: Runs local tests
    dir: /app
    cmd: vendor/bin/phpunit /app/tests
  phpunit-debug:
    service: appserver
    description: Runs local tests with xdebug
    dir: /app
    cmd: XDEBUG_CONFIG="start_with_request=yes" vendor/bin/phpunit /app/tests