FROM golang:latest as build-stage

WORKDIR /app

COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /cc-search

FROM alpine:latest AS release-stage
WORKDIR /
COPY --from=build-stage /cc-search /cc-search
EXPOSE 80
ENTRYPOINT [ "/cc-search" ]